"""
Django settings for Innovicloud project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env (sits one level above this file's directory)
load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is not set. Check your .env file.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'waytoinbox.com,www.waytoinbox.com').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'Email_validate_app',
    'django_apscheduler',
    "django_celery_results",
    "django_celery_beat",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'Email_validate_app.middleware.ContentSecurityPolicyMiddleware',  # INF-01
    'Email_validate_app.middleware.RequestIDMiddleware',
    'Email_validate_app.middleware.RequestLoggingMiddleware',
    'Email_validate_app.middleware.UnhandledExceptionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'Email_validate_app.middleware.SessionExpiryMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Innovicloud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "Email_validate_app" / "templates", BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Email_validate_app.context_processors.nav_credits',
            ],
        },
    },
]



WSGI_APPLICATION = 'Innovicloud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'Innovicloud'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        # INF-16: reuse DB connections across requests; reduces per-request connection
        # overhead and limits the blast radius of connection-flooding DoS attempts.
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
    }
}


AUTH_USER_MODEL = 'Email_validate_app.UserTable'




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR / "static"]



# Static files settings
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "Email_validate_app/static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# INF-14: route Django's 500-error emails to the ops team in production.
# Set DJANGO_ADMINS="Name:email@domain.com" (comma-separated for multiple).
SERVER_EMAIL = os.environ.get('SERVER_EMAIL') or EMAIL_HOST_USER
EMAIL_SUBJECT_PREFIX = '[Waytoinbox] '
def _parse_admins(raw):
    result = []
    for entry in raw.split(','):
        entry = entry.strip()
        if ':' in entry:
            name, addr = entry.split(':', 1)
            result.append((name.strip(), addr.strip()))
    return result

ADMINS = _parse_admins(os.environ.get('DJANGO_ADMINS', ''))



SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_SAVE_EVERY_REQUEST = True
# INF-12: rename from the Django default 'sessionid' so the framework is not
# immediately visible in network traffic or error messages
SESSION_COOKIE_NAME = 'sid'
# INF-13: cache-backed sessions auto-expire in Redis (no unbounded table growth);
# 'cached_db' also writes to DB so sessions survive a Redis restart.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

PASSWORD_RESET_TIMEOUT = 3600  # Email verification link expiry: 1 hour

LOGIN_URL = '/login/'

CSRF_FAILURE_VIEW = 'Email_validate_app.views.errors.csrf_failure'


# INF-02: Redis base URL — build from parts so REDIS_PASSWORD is never inline in .env
# Set REDIS_URL explicitly, or set REDIS_PASSWORD (+ optionally REDIS_HOST/REDIS_PORT).
_redis_password = os.environ.get("REDIS_PASSWORD", "")
_redis_host = os.environ.get("REDIS_HOST", "localhost")
_redis_port = os.environ.get("REDIS_PORT", "6379")

if os.environ.get("REDIS_URL"):
    REDIS_URL = os.environ["REDIS_URL"]
elif _redis_password:
    REDIS_URL = f"redis://:{_redis_password}@{_redis_host}:{_redis_port}"
else:
    REDIS_URL = f"redis://{_redis_host}:{_redis_port}"

# Django cache — Redis DB 2 (broker=0, results=1 are reserved for Celery)
# Used for distributed locks (e.g. CloudWatch sync per-campaign locking).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"{REDIS_URL}/2",
    }
}

# celery config

CELERY_BROKER_URL = f"{REDIS_URL}/0"
CELERY_RESULT_BACKEND = f"{REDIS_URL}/1"
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_SOFT_TIME_LIMIT = 300
CELERY_TASK_TIME_LIMIT = 360
# INF-10: expire task results after 1 hour — prevents email validation results
# (which contain personal email addresses) from accumulating in Redis indefinitely.
CELERY_TASK_RESULT_EXPIRES = 3600

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    # ── Every minute ────────────────────────────────────────────────────────
    "send_scheduled_campaigns_every_minute": {
        "task": "Email_validate_app.tasks.send_scheduled_campaigns.send_scheduled_campaigns",
        "schedule": crontab(minute="*"),
    },

    # ── Every 5 minutes ─────────────────────────────────────────────────────
    "sync_campaigns_cloudwatch_every_5m": {
        "task": "Email_validate_app.tasks.sync_campaigns_cloudwatch.sync_pending_campaigns",
        "schedule": crontab(minute="*/5"),
    },

    # ── Daily jobs ───────────────────────────────────────────────────────────
    "ip_blacklist_check_daily": {
        "task": "Email_validate_app.tasks.scheduler_job.scheduler_job",
        "schedule": crontab(hour=1, minute=0),       # 1 AM UTC
    },
    "domain_blacklist_check_daily": {
        "task": "Email_validate_app.tasks.scheduler_job.my_second_job",
        "schedule": crontab(hour=1, minute=30),      # 1:30 AM UTC
    },
    "update_all_reputations_daily": {
        "task": "Email_validate_app.tasks.update_reputations.update_all_reputations",
        "schedule": crontab(hour=2, minute=0),       # 2 AM UTC
    },
    "subscription_expiry_daily": {
        "task": "Email_validate_app.tasks.scheduler_job.subscription_expiry_job",
        "schedule": crontab(hour=2, minute=30),      # 2:30 AM UTC
    },
    "blacklist_notification_daily": {
        "task": "Email_validate_app.tasks.scheduler_job.bl_notification_job",
        "schedule": crontab(hour=3, minute=0),       # 3 AM UTC
    },
    "cleanup_expired_reports_daily": {
        "task": "Email_validate_app.tasks.generate_report.cleanup_expired_reports",
        "schedule": crontab(hour=4, minute=30),      # 4:30 AM UTC
    },
    # INF-13: purge expired rows from django_session (cached_db writes both Redis + DB)
    "clearsessions_daily": {
        "task": "Email_validate_app.tasks.clearsessions.clearsessions_task",
        "schedule": crontab(hour=5, minute=0),        # 5 AM UTC
    },
}



# Detect environment
ENVIRONMENT = os.environ.get("DJANGO_ENV", "local")

if ENVIRONMENT == "production":
    # Live server (Linux) — gevent works fine
    CELERY_WORKER_POOL = "gevent"

    # INF-02: Require Redis authentication in production
    if not _redis_password and "@" not in REDIS_URL.replace("redis://", "", 1):
        raise RuntimeError(
            "INF-02: REDIS_PASSWORD (or an authenticated REDIS_URL) must be set in production. "
            "An unauthenticated Redis allows cache bypass and Celery task injection."
        )

    # INF-03: Encrypt the MySQL connection in production
    _db_ssl_ca = os.environ.get("DB_SSL_CA")
    if _db_ssl_ca:
        DATABASES["default"]["OPTIONS"] = {"ssl_ca": _db_ssl_ca}
    else:
        import warnings as _warnings
        _warnings.warn(
            "INF-03: DB_SSL_CA is not set — the database connection is unencrypted. "
            "Set DB_SSL_CA to your CA certificate path in production.",
            RuntimeWarning,
            stacklevel=2,
        )

    # SEC-06: Secure cookie flags — only transmit cookies over HTTPS
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True
    SESSION_COOKIE_HTTPONLY = True   # JS cannot read the session cookie
    CSRF_COOKIE_HTTPONLY    = False  # Must be False — JS reads CSRF token for AJAX
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE    = 'Lax'

    # INF-08: Number of trusted reverse proxies in front of gunicorn (e.g. 1 for nginx).
    # Used by _get_client_ip() to pick the correct IP from X-Forwarded-For and
    # prevent rate-limit bypass via forged XFF headers.
    NUM_PROXIES = int(os.environ.get('NUM_PROXIES', '1'))

    # INF-07: Tell Django that nginx has already terminated SSL via X-Forwarded-Proto.
    # Without this, SecurityMiddleware sees every request as HTTP and triggers an
    # infinite redirect loop even though the client is on HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # SEC-07: Enforce HTTPS and HSTS
    SECURE_SSL_REDIRECT            = True
    SECURE_HSTS_SECONDS            = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD            = True

    # SEC-08: Security response headers
    SECURE_CONTENT_TYPE_NOSNIFF        = True   # X-Content-Type-Options: nosniff
    SECURE_REFERRER_POLICY             = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY  = 'same-origin'
else:
    # Local (Windows) — use solo
    CELERY_WORKER_POOL = "solo"




MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# INF-11: Store user-uploaded CSVs (email lists) outside MEDIA_ROOT so the web
# server never serves them directly. MEDIA_ROOT is mapped to /media/ by nginx;
# PRIVATE_UPLOAD_ROOT is intentionally NOT under that path.
PRIVATE_UPLOAD_ROOT = BASE_DIR / 'private_uploads'
PRIVATE_UPLOAD_ROOT.mkdir(exist_ok=True)



# Razorpay API credentials  (set rzp_test_* keys in .env for dev, rzp_live_* for production)
# SEC-09: Secret admin URL — set ADMIN_URL in .env (e.g. "mgt-xyz123/")
ADMIN_URL = os.environ.get('ADMIN_URL', 'admin/')

RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET')


# AWS SES — used to send campaign emails
AWS_SES_ACCESS_KEY_ID = os.environ.get('AWS_SES_ACCESS_KEY_ID')
AWS_SES_SECRET_ACCESS_KEY = os.environ.get('AWS_SES_SECRET_ACCESS_KEY')
AWS_SES_REGION = os.environ.get('AWS_SES_REGION', 'us-east-1')
AWS_SES_SOURCE_EMAIL = os.environ.get('AWS_SES_SOURCE_EMAIL')
AWS_SES_CONFIGURATION_SET = os.environ.get('AWS_SES_CONFIGURATION_SET', 'tracking-config')
SITE_URL = os.environ.get('SITE_URL', 'https://waytoinbox.com')

# Email provider: 'ses' (default) or 'mailgun'
EMAIL_PROVIDER  = os.environ.get('EMAIL_PROVIDER', 'ses')
MAILGUN_API_KEY = os.environ.get('MAILGUN_API_KEY', '')
MAILGUN_DOMAIN  = os.environ.get('MAILGUN_DOMAIN', '')
MAILGUN_BASE_URL = os.environ.get('MAILGUN_BASE_URL', 'https://api.mailgun.net')

# ── Email Campaign Batch Configuration ──────────────────
EMAIL_BATCH_SIZE             = int(os.environ.get('EMAIL_BATCH_SIZE',             '500'))
EMAIL_BATCH_DELAY            = int(os.environ.get('EMAIL_BATCH_DELAY',            '60'))
EMAIL_MAX_CONCURRENT_BATCHES = int(os.environ.get('EMAIL_MAX_CONCURRENT_BATCHES', '1'))
EMAIL_BATCH_RETRY_COUNT      = int(os.environ.get('EMAIL_BATCH_RETRY_COUNT',      '3'))
EMAIL_BATCH_RETRY_DELAY      = int(os.environ.get('EMAIL_BATCH_RETRY_DELAY',      '30'))

# ── Bulk Email Validation Configuration ─────────────────
EMAIL_VALIDATION_CONCURRENCY = int(os.environ.get('EMAIL_VALIDATION_CONCURRENCY', '150'))
EMAIL_VALIDATION_DAILY_LIMIT = int(os.environ.get('EMAIL_VALIDATION_DAILY_LIMIT', '5'))
EMAIL_VALIDATION_CHUNK_SIZE  = int(os.environ.get('EMAIL_VALIDATION_CHUNK_SIZE',  '500'))
EMAIL_VALIDATION_MAX_WORKERS = int(os.environ.get('EMAIL_VALIDATION_MAX_WORKERS', '50'))

# ── Filter Configuration ─────────────────────────────────
FILTER_SEARCH_DEBOUNCE_MS = int(os.environ.get('FILTER_SEARCH_DEBOUNCE_MS', '300'))
FILTER_DEFAULT_PAGE_SIZE  = int(os.environ.get('FILTER_DEFAULT_PAGE_SIZE',  '25'))
FILTER_MAX_PAGE_SIZE      = int(os.environ.get('FILTER_MAX_PAGE_SIZE',      '100'))
FILTER_SLOW_QUERY_MS      = int(os.environ.get('FILTER_SLOW_QUERY_MS',      '500'))

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# INF-04: DEBUG in dev, INFO in production — prevents internal state / table names leaking to log files
_APP_LOG_LEVEL = 'DEBUG' if DEBUG else 'INFO'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} rid={request_id} uid={user_id} | {message}',
            'style': '{',
            'defaults': {'request_id': '-', 'user_id': '-'},
        },
        'simple': {
            'format': '[{levelname}] {name} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'app_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'level': 'ERROR',
            'formatter': 'verbose',
        },
        'task_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'tasks.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'Email_validate_app.views': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': _APP_LOG_LEVEL,
            'propagate': False,
        },
        'Email_validate_app.services': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': _APP_LOG_LEVEL,
            'propagate': False,
        },
        'Email_validate_app.tasks': {
            'handlers': ['console', 'task_file', 'error_file'],
            'level': _APP_LOG_LEVEL,
            'propagate': False,
        },
        'Email_validate_app': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'error_file'],
        'level': 'WARNING',
    },
}