# Generated by Django 5.1.7 on 2025-03-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_email', models.EmailField(max_length=225, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reset_token', models.CharField(blank=True, max_length=225, null=True)),
                ('reset_token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
