# Generated by Django 5.1.6 on 2025-03-20 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0004_rename_user_password_usertable_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('job_status', models.CharField(blank=True, max_length=225, null=True)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('valid_count', models.IntegerField(blank=True, null=True)),
                ('invalid_count', models.IntegerField(blank=True, null=True)),
                ('unknown_count', models.IntegerField(blank=True, null=True)),
                ('others_count', models.IntegerField(blank=True, null=True)),
                ('valid_percentage', models.FloatField(blank=True, null=True)),
                ('invalid_percentage', models.FloatField(blank=True, null=True)),
                ('unknown_percentage', models.FloatField(blank=True, null=True)),
                ('others_percentage', models.IntegerField(blank=True, null=True)),
                ('credite_status', models.CharField(blank=True, max_length=200, null=True)),
                ('free_analyze', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'list_files',
            },
        ),
    ]
