# Generated by Django 5.1.7 on 2025-04-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0006_validatedemails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidatedEmails',
        ),
    ]
