# Generated by Django 5.1.7 on 2025-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0007_delete_validatedemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfiles',
            name='insert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
