# Generated by Django 5.1.7 on 2025-04-22 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0009_currentcredits_totalcredits_usedcredits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=225, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=225, null=True)),
                ('payer_id', models.CharField(blank=True, max_length=225, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=225, null=True)),
                ('payer_email', models.CharField(blank=True, max_length=225, null=True)),
                ('payer_address', models.CharField(blank=True, max_length=225, null=True)),
                ('payer_method', models.CharField(blank=True, max_length=225, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=225, null=True)),
                ('amount', models.CharField(blank=True, max_length=225, null=True)),
                ('currency', models.CharField(blank=True, max_length=225, null=True)),
                ('credits', models.CharField(blank=True, max_length=225, null=True)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
