# Generated by Django 5.1.7 on 2025-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0012_blocklistmonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklists',
            fields=[
                ('Blacklists_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Blacklists_name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'blacklists',
            },
        ),
    ]
