# Generated by Django 5.1.7 on 2025-05-02 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0013_blacklists'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ips', models.CharField(max_length=225)),
                ('blacklists_name', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_statuses', to='Email_validate_app.blocklistmonitor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklist Status',
                'verbose_name_plural': 'Blacklist Statuses',
                'db_table': 'blacklist_status',
            },
        ),
    ]
