# Generated by Django 5.1.7 on 2025-05-09 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0015_blacklistlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistmonitor',
            name='last_monitor_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blocklistmonitor',
            name='listed_count',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
