# Generated by Django 5.1.7 on 2025-05-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0016_blocklistmonitor_last_monitor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklistmonitor',
            name='last_monitor_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
