# Generated by Django 5.1.7 on 2025-05-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0017_alter_blocklistmonitor_last_monitor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistlisted',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blackliststatus',
            name='user',
        ),
    ]
