# Generated by Django 5.1.7 on 2025-10-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0023_subspayment_plan_status_subspayment_valid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subspayment',
            name='valid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
