# Generated by Django 6.0.3 on 2026-03-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0025_domainblacklistlisted_domainblackliststatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainblacklistlisted',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_blacklist_listed', to='Email_validate_app.domainblocklist'),
        ),
        migrations.AlterField(
            model_name='domainblackliststatus',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_blacklist_statuses', to='Email_validate_app.domainblocklist'),
        ),
    ]
