# Generated by Django 6.0.3 on 2026-04-03 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0027_domainblacklists'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_header', models.TextField()),
                ('origin_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
