# Generated by Django 6.0.3 on 2026-04-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0028_emailheader'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailheader',
            table='EmailHeader',
        ),
    ]
