# Generated by Django 6.0.3 on 2026-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0034_emailvalidate_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subspayment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
