# Generated by Django 6.0.3 on 2026-05-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0037_all_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allemails',
            old_name='insert_date',
            new_name='completed_time',
        ),
    ]
