# Generated by Django 6.0.3 on 2026-05-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0039_usertable_company_usertable_role_usertable_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='notify_blocklist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='notify_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='notify_job_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='notify_payment',
            field=models.BooleanField(default=True),
        ),
    ]
