# Generated by Django 6.0.3 on 2026-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0043_reputation_reputationresults'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='allemails',
            name='all_emails_file_id_09f128_idx',
        ),
        migrations.AddIndex(
            model_name='allemails',
            index=models.Index(fields=['user', 'file_id'], name='all_emails_user_id_326fab_idx'),
        ),
        migrations.AddIndex(
            model_name='allemails',
            index=models.Index(fields=['file_id', 'validation_results'], name='all_emails_file_id_a575c1_idx'),
        ),
    ]
