# Generated by Django 6.0.3 on 2026-06-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0049_add_campaign_list_and_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignemail',
            old_name='user_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='campaignemail',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaignlist',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
    ]
