# Generated by Django 6.0.3 on 2026-06-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0051_templatelibrary_usertemplate_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
