# Generated by Django 6.0.3 on 2026-06-21 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0054_campaign_last_cloudwatch_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
            ],
            options={
                'db_table': 'login_activity',
                'ordering': ['-login_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='campaignevent',
            name='unique_campaign_event',
        ),
        migrations.RenameIndex(
            model_name='campaignevent',
            new_name='campaign_ev_campaig_210bca_idx',
            old_name='campaign_ev_campaig_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignevent',
            new_name='campaign_ev_message_46d991_idx',
            old_name='campaign_ev_message_idx',
        ),
        migrations.AlterUniqueTogether(
            name='campaignevent',
            unique_together={('message_id', 'email', 'event_type')},
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
