# Generated by Django 6.0.3 on 2026-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0068_campaignstats_unsubscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignlist',
            old_name='subscribe_count',
            new_name='subscribed_count',
        ),
        migrations.AddField(
            model_name='campaignlist',
            name='unsubscribed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignevent',
            name='event_type',
            field=models.CharField(choices=[('send', 'Send'), ('delivery', 'Delivery'), ('open', 'Open'), ('click', 'Click'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('reject', 'Reject'), ('unsubscribe', 'Unsubscribe')], max_length=20),
        ),
    ]
