# Generated by Django 6.0.3 on 2026-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0073_add_design_json_to_template_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='used_in_campaign',
            field=models.BooleanField(default=False),
        ),
    ]
