# Generated by Django 6.0.3 on 2026-07-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0074_usertemplate_is_campaign_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcredits',
            name='cc_current_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentcredits',
            name='cc_total_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentcredits',
            name='cc_used_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subspayment',
            name='cc_credits',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='totalcredits',
            name='cc_buying_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalcredits',
            name='cc_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedcredits',
            name='cc_used_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedcredits',
            name='cc_used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
