# Generated by Django 6.0.3 on 2026-07-20 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0079_add_filter_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMARCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('spf_status', models.CharField(max_length=10)),
                ('dmarc_status', models.CharField(max_length=10)),
                ('dkim_status', models.CharField(max_length=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dmarc_analysis',
            },
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='camp_user_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaignemail',
            name='ce_list_sub_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailvalidate',
            name='ev_user_date_hidden_idx',
        ),
        migrations.RemoveIndex(
            model_name='reputation',
            name='rep_user_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='creditauditlog',
            new_name='credit_audi_user_id_713f70_idx',
            old_name='credit_audi_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='creditauditlog',
            new_name='credit_audi_ref_typ_685116_idx',
            old_name='credit_audi_ref_type_idx',
        ),
        migrations.AlterField(
            model_name='creditauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmarc_analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
