# Generated by Django 6.0.3 on 2026-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0080_dmarc_analysis_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmarcanalysis',
            name='analysis_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='dkim_record',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='dkim_selector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='dmarc_alignment_dkim',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='dmarc_alignment_spf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='dmarc_policy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='dmarc_record',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='dmarc_rua',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='dmarc_ruf',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='dmarc_subdomain_policy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='spf_includes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dmarcanalysis',
            name='spf_record',
            field=models.TextField(blank=True, null=True),
        ),
    ]
