# Generated by Django 6.0.3 on 2026-07-21 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0082_notify_campaign_reputation_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
