# Generated by Django 6.0.3 on 2026-07-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0083_add_report_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportJob',
        ),
    ]
