# Generated by Django 6.0.3 on 2026-07-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0086_senderdomain_dual_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlist',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
