# Generated by Django 6.0.3 on 2026-07-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0090_usernotification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfiles',
            name='job_status',
            field=models.CharField(blank=True, db_index=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='subspayment',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='subspayment',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='reset_token',
            field=models.CharField(blank=True, db_index=True, max_length=225, null=True),
        ),
        migrations.AddIndex(
            model_name='emailvalidate',
            index=models.Index(fields=['user', 'insert_date'], name='ev_user_date_idx'),
        ),
    ]
