# Generated by Django 5.1.7 on 2025-03-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertable',
            table='user_table',
        ),
    ]
