# Generated by Django 5.1.7 on 2025-03-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0002_alter_usertable_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
