# Generated by Django 5.1.7 on 2025-04-19 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0008_alter_listfiles_insert_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCredits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_credits', models.IntegerField(blank=True, null=True)),
                ('used_credits', models.IntegerField(blank=True, null=True)),
                ('current_credits', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'current_credits',
            },
        ),
        migrations.CreateModel(
            name='TotalCredits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buying_credits', models.IntegerField(blank=True, null=True)),
                ('buying_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'total_credits',
            },
        ),
        migrations.CreateModel(
            name='UsedCredits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('used_credits', models.IntegerField(blank=True, null=True)),
                ('used_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'used_credits',
            },
        ),
    ]
