# Generated by Django 5.1.7 on 2025-04-24 06:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('mx_found', models.CharField(max_length=225)),
                ('mx_record', models.CharField(max_length=225)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_validate',
            },
        ),
    ]
