# Generated by Django 5.1.7 on 2025-05-02 05:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0011_emailvalidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocklistMonitor',
            fields=[
                ('ip_id', models.AutoField(primary_key=True, serialize=False)),
                ('ips', models.CharField(max_length=225)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocklist_monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocklist Monitor',
                'verbose_name_plural': 'Blocklist Monitors',
                'db_table': 'blocklist_monitor',
            },
        ),
    ]
