# Generated by Django 5.1.7 on 2025-05-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0018_remove_blacklistlisted_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklists',
            name='dnsbl_domain',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
