# Generated by Django 5.1.7 on 2025-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0020_subspayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcredits',
            name='ip_current_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentcredits',
            name='ip_total_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentcredits',
            name='ip_used_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalcredits',
            name='ip_buying_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalcredits',
            name='ip_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedcredits',
            name='used_ip_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usedcredits',
            name='used_ip_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
