# Generated by Django 5.1.7 on 2025-10-30 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0022_emailvalidationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subspayment',
            name='plan_status',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='subspayment',
            name='valid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
