# Generated by Django 6.0.3 on 2026-03-26 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0024_alter_subspayment_valid_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainBlacklistListed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.CharField(max_length=225)),
                ('blacklists_name', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_blacklist_listed', to='Email_validate_app.blocklistmonitor')),
            ],
            options={
                'verbose_name': 'Domain Blacklist Listed',
                'verbose_name_plural': 'Domain Blacklist Listed',
                'db_table': 'domain_blacklist_listed',
            },
        ),
        migrations.CreateModel(
            name='DomainBlacklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.CharField(max_length=225)),
                ('blacklists_name', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_blacklist_statuses', to='Email_validate_app.blocklistmonitor')),
            ],
            options={
                'verbose_name': 'Domain Blacklist Status',
                'verbose_name_plural': 'Domain Blacklist Statuses',
                'db_table': 'domain_blacklist_status',
            },
        ),
        migrations.CreateModel(
            name='DomainBlocklist',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=225)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('last_monitor_date', models.DateTimeField(blank=True, null=True)),
                ('listed_count', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_blocklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain Blocklist',
                'verbose_name_plural': 'Domain Blocklist',
                'db_table': 'domain_blocklist',
            },
        ),
    ]
