# Generated by Django 6.0.3 on 2026-03-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0026_alter_domainblacklistlisted_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainBlacklists',
            fields=[
                ('Blacklists_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Blacklists_name', models.CharField(max_length=225)),
                ('dnsbl_domain', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'domainblacklists',
            },
        ),
    ]
