# Generated by Django 6.0.3 on 2026-04-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0029_alter_emailheader_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailvalidationlog',
            table='EmailValidationLog',
        ),
    ]
