# Generated by Django 6.0.3 on 2026-04-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0031_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfiles',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listfiles',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
