# Generated by Django 6.0.3 on 2026-05-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0033_remove_username_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalidate',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
