# Generated by Django 6.0.3 on 2026-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0035_payment_is_hidden_subspayment_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistmonitor',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domainblocklist',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
