# Generated by Django 6.0.3 on 2026-05-18 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0036_blocklistmonitor_is_hidden_domainblocklist_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(db_index=True)),
                ('table_name', models.CharField(db_index=True, max_length=225)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('validation_results', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'all_emails',
                'indexes': [models.Index(fields=['file_id', 'email'], name='all_emails_file_id_09f128_idx')],
                'unique_together': {('file_id', 'email')},
            },
        ),
    ]
