# Generated by Django 6.0.3 on 2026-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0038_rename_insert_date_allemails_completed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
