# Generated by Django 6.0.3 on 2026-06-08 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0042_usertable_password_changed_at_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation',
            },
        ),
        migrations.CreateModel(
            name='ReputationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField()),
                ('spam_rate', models.FloatField(blank=True, null=True)),
                ('domain_reputation', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_reputation', models.JSONField(blank=True, default=list)),
                ('delivery_errors', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_results',
                'indexes': [models.Index(fields=['user', 'domain', 'date'], name='reputation__user_id_68856b_idx')],
            },
        ),
    ]
