# Generated by Django 6.0.3 on 2026-06-13 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_rep_results_leftovers(apps, schema_editor):
    """
    Migration 0047 dropped reputation_id, user_id, and the old index via raw SQL.
    Django's state still tracks them, so we reconcile here safely.
    """
    with schema_editor.connection.cursor() as cursor:
        # Drop old index if it still exists
        cursor.execute("""
            SELECT INDEX_NAME FROM INFORMATION_SCHEMA.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME   = 'reputation_results'
              AND INDEX_NAME   = 'reputation__user_id_68856b_idx'
        """)
        if cursor.fetchone():
            cursor.execute(
                "DROP INDEX `reputation__user_id_68856b_idx` ON `reputation_results`"
            )

        # Drop FK constraints for reputation_id / user_id if they still exist
        cursor.execute("""
            SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME   = 'reputation_results'
              AND REFERENCED_TABLE_NAME IS NOT NULL
              AND COLUMN_NAME IN ('reputation_id', 'user_id')
        """)
        for (fk,) in cursor.fetchall():
            cursor.execute(
                f"ALTER TABLE `reputation_results` DROP FOREIGN KEY `{fk}`"
            )

        # Drop columns if they still exist
        cursor.execute("""
            SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME   = 'reputation_results'
              AND COLUMN_NAME IN ('reputation_id', 'user_id')
        """)
        for (col,) in cursor.fetchall():
            cursor.execute(
                f"ALTER TABLE `reputation_results` DROP COLUMN `{col}`"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0048_rename_rep_results_domain_date_idx_reputation__domain_161dc4_idx'),
    ]

    operations = [
        # Safely reconcile leftover reputation_results columns/index from migration 0047
        migrations.RunPython(
            drop_rep_results_leftovers,
            migrations.RunPython.noop,
        ),
        # Sync Django model state (no SQL executed — columns already gone)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='reputationresults',
                    name='reputation__user_id_68856b_idx',
                ),
                migrations.RemoveField(
                    model_name='reputationresults',
                    name='reputation',
                ),
                migrations.RemoveField(
                    model_name='reputationresults',
                    name='user',
                ),
            ],
            database_operations=[],  # already done above via RunPython
        ),
        # Create CampaignList
        migrations.CreateModel(
            name='CampaignList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=255)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('subscribe_count', models.PositiveIntegerField(default=0)),
                ('unsubscribe_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_list',
            },
        ),
        # Create CampaignEmail
        migrations.CreateModel(
            name='CampaignEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subscribed', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='Email_validate_app.campaignlist')),
            ],
            options={
                'db_table': 'campaign_emails',
            },
        ),
    ]
