# Generated by Django 6.0.3 on 2026-06-16 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0050_rename_user_name_campaignemail_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('newsletter', 'Newsletter'), ('promotion', 'Promotion'), ('welcome', 'Welcome'), ('announcement', 'Announcement'), ('event', 'Event'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('html_content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='template_library/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'template_library',
            },
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('html_content', models.TextField()),
                ('design_json', models.JSONField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='user_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('library_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Email_validate_app.templatelibrary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_templates',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_email', models.EmailField(max_length=254)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Email_validate_app.campaignlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Email_validate_app.usertemplate')),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
    ]
