# Generated by Django 6.0.3 on 2026-06-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0056_campaign_test_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntestsend',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
