# Generated by Django 6.0.3 on 2026-07-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0072_adminactivity_appsetting_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelibrary',
            name='design_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
