# Generated by Django 6.0.3 on 2026-07-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0081_dmarc_analysis_expand'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='notify_campaign',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='notify_reputation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='notify_sender_verify',
            field=models.BooleanField(default=True),
        ),
    ]
