# Generated by Django 6.0.3 on 2026-07-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0084_remove_report_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailheader',
            name='dkim_status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='emailheader',
            name='dmarc_status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='emailheader',
            name='risk_level',
            field=models.CharField(choices=[('SAFE', 'Safe'), ('RISKY', 'Risky'), ('DANGEROUS', 'Dangerous')], default='SAFE', max_length=10),
        ),
        migrations.AddField(
            model_name='emailheader',
            name='spam_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailheader',
            name='spf_status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
