# Generated by Django 6.0.3 on 2026-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0087_add_status_to_campaign_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sent_via',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
