# Generated by Django 6.0.3 on 2026-07-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0092_db10_api_key_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
