# Generated by Django 6.0.3 on 2026-07-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0093_alter_apikey_key_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subspayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
