# Generated by Django 6.0.3 on 2026-08-14 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0097_campaign_exclude_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft 365')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('daily_limit', models.IntegerField(default=500)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('failed', 'Failed'), ('unchecked', 'Unchecked')], default='unchecked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='guestactivity',
            new_name='guest_activ_ip_addr_f24512_idx',
            old_name='guest_act_ip_type_idx',
        ),
        migrations.RenameIndex(
            model_name='guestactivity',
            new_name='guest_activ_created_17c8b0_idx',
            old_name='guest_act_created_idx',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
