# Generated by Django 5.1.7 on 2026-08-15 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0098_email_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOEmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft 365')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_ssl', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('daily_limit', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('failed', 'Failed'), ('unchecked', 'Unchecked')], default='unchecked', max_length=20)),
                ('warmup_enabled', models.BooleanField(default=False)),
                ('last_imap_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'so_email_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOEmailAccountWarmup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target', models.IntegerField(default=40)),
                ('daily_current', models.IntegerField(default=2)),
                ('ramp_up_days', models.IntegerField(default=30)),
                ('ramp_up_increment', models.IntegerField(default=2)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warmup', to='Email_validate_app.soemailaccount')),
            ],
            options={
                'db_table': 'so_email_account_warmups',
            },
        ),
        migrations.CreateModel(
            name='SOList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'so_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('preview_text', models.CharField(blank=True, max_length=200)),
                ('html_body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_delivered', models.PositiveIntegerField(default=0)),
                ('total_opened', models.PositiveIntegerField(default=0)),
                ('total_clicked', models.PositiveIntegerField(default=0)),
                ('total_replied', models.PositiveIntegerField(default=0)),
                ('total_unsubscribed', models.PositiveIntegerField(default=0)),
                ('total_bounced', models.PositiveIntegerField(default=0)),
                ('total_complained', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_campaigns', to=settings.AUTH_USER_MODEL)),
                ('recipient_lists', models.ManyToManyField(blank=True, db_table='so_campaign_lists', related_name='campaigns', to='Email_validate_app.solist')),
            ],
            options={
                'db_table': 'so_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], default='active', max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'so_prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOListProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('so_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_prospects', to='Email_validate_app.solist')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_lists', to='Email_validate_app.soprospect')),
            ],
            options={
                'db_table': 'so_list_prospects',
            },
        ),
        migrations.CreateModel(
            name='SOEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('replied', 'Replied'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Email_validate_app.socampaign')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_events', to='Email_validate_app.soprospect')),
            ],
            options={
                'db_table': 'so_events',
            },
        ),
        migrations.CreateModel(
            name='SOCampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('tracking_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='Email_validate_app.socampaign')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_contacts', to='Email_validate_app.soprospect')),
            ],
            options={
                'db_table': 'so_campaign_contacts',
            },
        ),
        migrations.CreateModel(
            name='SOTrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('destination_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_links', to='Email_validate_app.socampaigncontact')),
            ],
            options={
                'db_table': 'so_tracked_links',
            },
        ),
        migrations.CreateModel(
            name='SOEmailAccountRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_rotations', to='Email_validate_app.soemailaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_rotations', to='Email_validate_app.socampaign')),
            ],
            options={
                'db_table': 'so_email_account_rotations',
                'ordering': ['order'],
                'unique_together': {('campaign', 'account')},
            },
        ),
        migrations.AddIndex(
            model_name='soprospect',
            index=models.Index(fields=['user', 'email'], name='so_prospect_user_id_7f8b92_idx'),
        ),
        migrations.AddIndex(
            model_name='soprospect',
            index=models.Index(fields=['user', 'status'], name='so_prospect_user_id_7e0e36_idx'),
        ),
        migrations.AddIndex(
            model_name='soprospect',
            index=models.Index(fields=['email'], name='so_prospect_email_c35043_idx'),
        ),
        migrations.AddIndex(
            model_name='soprospect',
            index=models.Index(fields=['status'], name='so_prospect_status_6e59f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='solistprospect',
            unique_together={('so_list', 'prospect')},
        ),
        migrations.AddIndex(
            model_name='soevent',
            index=models.Index(fields=['campaign', 'email', 'event_type'], name='so_events_campaig_52a278_idx'),
        ),
        migrations.AddIndex(
            model_name='soevent',
            index=models.Index(fields=['campaign', 'event_type'], name='so_events_campaig_bb56ac_idx'),
        ),
        migrations.AddIndex(
            model_name='socampaigncontact',
            index=models.Index(fields=['campaign', 'status'], name='so_campaign_campaig_2f3e80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socampaigncontact',
            unique_together={('campaign', 'email')},
        ),
    ]
