# Generated by Django 5.1.7 on 2026-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0105_drop_orphan_listprospect_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='socampaigncontact',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socampaigncontact',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socampaigncontact',
            name='current_step',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socampaigncontact',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socampaigncontact',
            name='variant_label',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='socampaigncontact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('sending', 'Sending'), ('sent', 'Sent'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='socampaigncontact',
            index=models.Index(fields=['status', 'next_action_at'], name='so_cc_status_next_idx'),
        ),
    ]
