# Generated by Django 5.1.7 on 2026-08-19 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0106_so_sequence_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='socampaigncontact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_campaign_contacts', to='Email_validate_app.soemailaccount'),
        ),
        migrations.CreateModel(
            name='SOEmailAccountDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='Email_validate_app.soemailaccount')),
            ],
            options={
                'db_table': 'so_email_account_daily_usage',
                'unique_together': {('account', 'date')},
            },
        ),
    ]
