# Generated by Django 5.1.7 on 2026-08-19 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0107_so_campaign_contact_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='socampaign',
            name='send_hour_end',
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AddField(
            model_name='socampaign',
            name='send_hour_start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='socampaign',
            name='send_weekdays',
            field=models.CharField(default='mon,tue,wed,thu,fri,sat,sun', max_length=27),
        ),
    ]
