# Generated by Django 5.1.7 on 2026-08-19 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0108_so_campaign_send_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('is_unread', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('classification', models.CharField(blank=True, choices=[('interested', 'Interested'), ('meeting', 'Meeting'), ('question', 'Question'), ('not_interested', 'Not Interested'), ('out_of_office', 'Out of Office'), ('unsubscribe', 'Unsubscribed'), ('wrong_person', 'Wrong Person'), ('positive', 'Positive'), ('negative', 'Negative')], default='', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=300)),
                ('last_message_direction', models.CharField(blank=True, choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='Email_validate_app.soemailaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='Email_validate_app.socampaign')),
                ('campaign_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='Email_validate_app.socampaigncontact')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_conversations', to='Email_validate_app.soprospect')),
            ],
            options={
                'db_table': 'so_conversations',
            },
        ),
        migrations.CreateModel(
            name='SOConversationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Email_validate_app.soconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_conversation_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'so_conversation_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#0099CC', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'so_tags',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='soconversation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='Email_validate_app.sotag'),
        ),
        migrations.CreateModel(
            name='SOMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('is_sequence_step', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('from_email', models.CharField(max_length=255)),
                ('to_email', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('has_attachments', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Email_validate_app.soconversation')),
            ],
            options={
                'db_table': 'so_messages',
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='so_messages_convers_8319a3_idx'), models.Index(fields=['message_id'], name='so_messages_message_9caeeb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='soconversation',
            index=models.Index(fields=['campaign', 'is_unread'], name='so_conversa_campaig_cdce85_idx'),
        ),
        migrations.AddIndex(
            model_name='soconversation',
            index=models.Index(fields=['campaign', 'classification'], name='so_conversa_campaig_ce912b_idx'),
        ),
        migrations.AddIndex(
            model_name='soconversation',
            index=models.Index(fields=['campaign', 'is_archived'], name='so_conversa_campaig_988a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='soconversation',
            index=models.Index(fields=['-last_message_at'], name='so_conversa_last_me_729197_idx'),
        ),
    ]
