# Generated by Django 5.1.7 on 2026-08-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0109_so_inbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSubsequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trigger_type', models.CharField(choices=[('no_reply', 'No reply')], default='no_reply', max_length=20)),
                ('trigger_days', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsequences', to='Email_validate_app.socampaign')),
            ],
            options={
                'db_table': 'so_subsequences',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='socampaigncontact',
            name='active_subsequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequence_contacts', to='Email_validate_app.sosubsequence'),
        ),
        migrations.CreateModel(
            name='SOSubsequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('wait_days', models.PositiveIntegerField(default=0)),
                ('wait_hours', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Email_validate_app.sosubsequence')),
            ],
            options={
                'db_table': 'so_subsequence_steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SOSubsequenceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='A', max_length=2)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('preheader', models.CharField(blank=True, default='', max_length=200)),
                ('html_body', models.TextField(blank=True, default='')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Email_validate_app.sosubsequencestep')),
            ],
            options={
                'db_table': 'so_subsequence_variants',
                'ordering': ['label'],
            },
        ),
        migrations.AddIndex(
            model_name='sosubsequence',
            index=models.Index(fields=['campaign', 'order'], name='so_subseq_camp_order_idx'),
        ),
        migrations.AddIndex(
            model_name='sosubsequencestep',
            index=models.Index(fields=['subsequence', 'order'], name='so_substep_seq_order_idx'),
        ),
    ]
