# Generated by Django 5.1.7 on 2026-08-21 05:27, hand-restructured.
#
# Relaxes SOConversation's hard campaign coupling (Sales Outreach Unibox
# upgrade — the Inbox needs to show all mail from a connected account, not
# only campaign replies). `thread_key` becomes the real grouping/dedup
# identity: 'cc:<campaign_contact_id>' for campaign-linked threads (preserves
# exactly the uniqueness the old required OneToOne gave), 'acct:<account_id>:
# <email>' for everything else. MySQL doesn't support conditional/partial
# unique indexes, so thread_key is added non-unique, backfilled for every
# existing row (all of which have campaign_contact set today), and only then
# altered to unique — never a moment where the column is unique with
# colliding blank values in it.
#
# Same shape for SOMessage.message_id -> nullable: NULL (not '') is required
# once (account, message_id) becomes a real unique constraint, since MySQL
# treats repeated '' as duplicates but allows unlimited NULLs, and headerless
# inbound mail already produces '' today.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0110_so_subsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='soemailaccount',
            name='sent_folder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),

        # thread_key: add non-unique first, backfill, then lock down.
        migrations.AddField(
            model_name='soconversation',
            name='thread_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.RunSQL(
            sql="UPDATE so_conversations SET thread_key = CONCAT('cc:', campaign_contact_id) "
                "WHERE thread_key = '' OR thread_key IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='soconversation',
            name='thread_key',
            field=models.CharField(db_index=True, max_length=300, unique=True),
        ),

        # Relax the hard campaign coupling.
        migrations.AlterField(
            model_name='soconversation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='Email_validate_app.socampaign'),
        ),
        migrations.AlterField(
            model_name='soconversation',
            name='campaign_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='Email_validate_app.socampaigncontact'),
        ),

        # message_id: nullable, then normalize existing '' to NULL before the
        # new unique constraint goes on (below).
        migrations.AlterField(
            model_name='somessage',
            name='message_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE so_messages SET message_id = NULL WHERE message_id = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # New denormalized SOMessage.account, backfilled from its conversation,
        # then the real DB-level Message-ID dedup guarantee.
        migrations.AddField(
            model_name='somessage',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='Email_validate_app.soemailaccount'),
        ),
        migrations.RunSQL(
            sql="UPDATE so_messages m INNER JOIN so_conversations c ON m.conversation_id = c.id "
                "SET m.account_id = c.account_id WHERE m.account_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterUniqueTogether(
            name='somessage',
            unique_together={('account', 'message_id')},
        ),

        # New account-scoped indexes — views/so_inbox.py's _base_qs now scopes
        # by account rather than campaign.
        migrations.AddIndex(
            model_name='soconversation',
            index=models.Index(fields=['account', 'is_unread'], name='so_conversa_account_90ad02_idx'),
        ),
        migrations.AddIndex(
            model_name='soconversation',
            index=models.Index(fields=['account', 'is_archived'], name='so_conversa_account_ab98d3_idx'),
        ),
        migrations.AddIndex(
            model_name='soconversation',
            index=models.Index(fields=['account', 'classification'], name='so_conversa_account_d22376_idx'),
        ),
    ]
