# Generated by Django 5.1.7 on 2026-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0111_so_inbox_unibox'),
    ]

    operations = [
        migrations.AddField(
            model_name='somessage',
            name='bcc_email',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='somessage',
            name='cc_email',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
