# Generated by Django 5.1.7 on 2026-08-24 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0112_somessage_cc_bcc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soemailaccountwarmup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='WarmupReceiverAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('paused', 'Paused'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_receiver_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warmup_receiver_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarmupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(blank=True, default='', max_length=255)),
                ('receiver_email', models.CharField(blank=True, default='', max_length=255)),
                ('identifier', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('checking', 'Checking'), ('completed', 'Completed'), ('send_failed', 'Send Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('landing_location', models.CharField(blank=True, choices=[('inbox', 'Inbox'), ('spam', 'Spam'), ('other', 'Other'), ('not_found', 'Not Found')], max_length=20, null=True)),
                ('rescued_to_inbox', models.BooleanField(default=False)),
                ('was_unread', models.BooleanField(blank=True, null=True)),
                ('marked_read', models.BooleanField(default=False)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('check_attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('check_after', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warmup_messages', to='Email_validate_app.soemailaccount')),
                ('receiver_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warmup_messages', to='Email_validate_app.warmupreceiveraccount')),
            ],
            options={
                'db_table': 'warmup_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarmupDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_daily_usage', to='Email_validate_app.soemailaccount')),
            ],
            options={
                'db_table': 'warmup_daily_usage',
                'unique_together': {('account', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='warmupreceiveraccount',
            index=models.Index(fields=['user', 'status'], name='warmup_rece_user_id_780b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupreceiveraccount',
            index=models.Index(fields=['user', 'deleted_at'], name='warmup_rece_user_id_e1e70d_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupreceiveraccount',
            index=models.Index(fields=['user', 'status', 'last_assigned_at'], name='warmup_rece_user_id_632076_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupmessage',
            index=models.Index(fields=['status', 'scheduled_for'], name='warmup_msg_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupmessage',
            index=models.Index(fields=['status', 'check_after'], name='warmup_msg_status_check_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupmessage',
            index=models.Index(fields=['sender_account', 'created_at'], name='warmup_msg_sender_created_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupmessage',
            index=models.Index(fields=['receiver_account', 'created_at'], name='warmup_msg_recv_created_idx'),
        ),
    ]
