# Generated by Django 5.1.7 on 2026-08-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0113_warmup_receivers_and_messages'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='warmupreceiveraccount',
            name='warmup_rece_user_id_780b9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='warmupreceiveraccount',
            name='warmup_rece_user_id_632076_idx',
        ),
        migrations.AddIndex(
            model_name='warmupreceiveraccount',
            index=models.Index(fields=['status', 'deleted_at'], name='warmup_rece_status_d7bc34_idx'),
        ),
        migrations.AddIndex(
            model_name='warmupreceiveraccount',
            index=models.Index(fields=['status', 'last_assigned_at'], name='warmup_rece_status_ecffc6_idx'),
        ),
    ]
