# Generated by Django 5.1.7 on 2026-08-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0114_remove_warmupreceiveraccount_warmup_rece_user_id_780b9c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='Email_validate_app.soemailaccount'),
        ),
        migrations.AddField(
            model_name='soevent',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
