# Generated by Django 5.1.7 on 2026-08-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0115_so_event_attribution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='somessage',
            unique_together={('account', 'message_id')},
        ),
        migrations.AddField(
            model_name='somessage',
            name='headerless_fingerprint',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='somessage',
            unique_together={('account', 'headerless_fingerprint'), ('account', 'message_id')},
        ),
    ]
