# Generated by Django 5.1.7 on 2026-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0116_so_message_headerless_dedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='socampaign',
            name='tracking_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
