# Generated by Django 5.1.7 on 2026-08-25 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0118_so_event_account_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='socampaigncontact',
            name='branch_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='socampaigncontact',
            name='last_condition_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='SOSequenceCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('no_event_after_days', 'No event after N days')], default='no_event_after_days', max_length=30)),
                ('wait_days', models.PositiveIntegerField(default=0)),
                ('event_count_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='Email_validate_app.socampaign')),
                ('no_target_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions_as_no_target', to='Email_validate_app.sosequencestep')),
                ('source_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions_as_source', to='Email_validate_app.sosequencestep')),
                ('yes_target_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions_as_yes_target', to='Email_validate_app.sosequencestep')),
            ],
            options={
                'db_table': 'so_sequence_conditions',
                'indexes': [models.Index(fields=['campaign', 'source_step'], name='so_seqcond_camp_step_idx')],
            },
        ),
    ]
