# Generated by Django 5.1.7 on 2026-08-25 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0122_alter_sosequencecondition_trigger_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOOpenPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('step_order', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_pixels', to='Email_validate_app.socampaigncontact')),
            ],
            options={
                'db_table': 'so_open_pixels',
                'unique_together': {('campaign_contact', 'step_order')},
            },
        ),
    ]
