# Generated by Django 5.1.7 on 2026-08-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0123_so_open_pixel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='soopenpixel',
            unique_together=set(),
        ),
    ]
