# Generated by Django 5.1.7 on 2026-08-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0124_so_open_pixel_drop_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosequencecondition',
            name='trigger_type',
            field=models.CharField(choices=[('no_event_after_days', 'No event after N days'), ('clicked', 'Clicked'), ('opened', 'Opened')], default='no_event_after_days', max_length=30),
        ),
    ]
