# Generated by Django 5.1.7 on 2026-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0125_alter_sosequencecondition_trigger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosequencecondition',
            name='trigger_type',
            field=models.CharField(choices=[('no_event_after_days', 'No event after N days'), ('clicked', 'Clicked'), ('opened', 'Opened'), ('replied', 'Replied')], default='no_event_after_days', max_length=30),
        ),
    ]
