# Generated by Django 5.1.7 on 2026-08-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0126_alter_sosequencecondition_trigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='socampaigncontact',
            name='last_condition_group_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='SOConditionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.CharField(choices=[('and', 'AND — every condition must be true'), ('or', 'OR — any condition may be true')], default='and', max_length=3)),
                ('wait_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Email_validate_app.socampaign')),
                ('no_target_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_groups_as_no_target', to='Email_validate_app.sosequencestep')),
                ('source_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_groups_as_source', to='Email_validate_app.sosequencestep')),
                ('yes_target_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_groups_as_yes_target', to='Email_validate_app.sosequencestep')),
            ],
            options={
                'db_table': 'so_condition_groups',
            },
        ),
        migrations.AddField(
            model_name='sosequencecondition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='Email_validate_app.soconditiongroup'),
        ),
        migrations.AddIndex(
            model_name='soconditiongroup',
            index=models.Index(fields=['campaign', 'source_step'], name='so_condgrp_camp_step_idx'),
        ),
    ]
