# Generated by Django 5.1.7 on 2026-09-01 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0128_sync_admin_staff_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_services',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cart_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='creditauditlog',
            name='credit_type',
            field=models.CharField(choices=[('vc', 'Validation Credits'), ('ac', 'Analysis Credits'), ('cc', 'Contact Credits'), ('email_validation', 'Email Validation'), ('email_marketing', 'Email Marketing'), ('sales_outreach', 'Sales Outreach'), ('reputation', 'Reputation Analysis'), ('header_analysis', 'Email Header Analyzer'), ('ip_blocklist', 'IP Blocklist Monitor'), ('domain_blocklist', 'Domain Blocklist Monitor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creditauditlog',
            name='ref_type',
            field=models.CharField(blank=True, choices=[('payg', 'Pay-As-You-Go Purchase'), ('subscription', 'Subscription Purchase'), ('validation', 'Email Validation'), ('campaign', 'Campaign Send'), ('ip_check', 'IP/Domain/Header/Reputation Check'), ('admin', 'Admin Adjustment'), ('service_purchase', 'Service Credit Purchase'), ('so_account', 'Sales Outreach Account Added')], max_length=30),
        ),
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('email_validation', 'Email Validation'), ('email_marketing', 'Email Marketing'), ('sales_outreach', 'Sales Outreach'), ('reputation', 'Reputation Analysis'), ('header_analysis', 'Email Header Analyzer'), ('ip_blocklist', 'IP Blocklist Monitor'), ('domain_blocklist', 'Domain Blocklist Monitor')], max_length=20)),
                ('mode', models.CharField(choices=[('tier', 'Flat tier price'), ('block', 'Price per block')], default='tier', max_length=10)),
                ('min_qty', models.BigIntegerField(blank=True, null=True)),
                ('max_qty', models.BigIntegerField(blank=True, null=True)),
                ('block_size', models.BigIntegerField(blank=True, null=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credit_packages',
                'ordering': ['service', 'sort_order'],
                'indexes': [models.Index(fields=['service', 'is_active', 'sort_order'], name='credit_pkg_svc_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='Email_validate_app.coupon')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='Email_validate_app.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_redemptions',
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['coupon', 'user'], name='coupon_redeem_cu_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('email_validation', 'Email Validation'), ('email_marketing', 'Email Marketing'), ('sales_outreach', 'Sales Outreach'), ('reputation', 'Reputation Analysis'), ('header_analysis', 'Email Header Analyzer'), ('ip_blocklist', 'IP Blocklist Monitor'), ('domain_blocklist', 'Domain Blocklist Monitor')], max_length=20)),
                ('balance', models.BigIntegerField(default=0)),
                ('total_purchased', models.BigIntegerField(default=0)),
                ('total_used', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_credits',
                'indexes': [models.Index(fields=['user'], name='svc_credit_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'service'), name='uniq_service_credit_user_service'), models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='service_credit_balance_nonneg')],
            },
        ),
    ]
