# Generated by Django 5.1.7 on 2026-09-01 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0130_seed_credit_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=225, unique=True)),
                ('cart_json', models.JSONField()),
                ('subtotal_cents', models.BigIntegerField(default=0)),
                ('discount_cents', models.BigIntegerField(default=0)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('promo_code', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order', to='Email_validate_app.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_orders',
                'indexes': [models.Index(fields=['user', 'status'], name='svc_order_user_status_idx')],
            },
        ),
    ]
