# Generated by Django 5.1.7 on 2026-09-01 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0131_service_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='Email_validate_app.coupon'),
        ),
    ]
