# Generated by Django 5.1.7 on 2026-09-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0132_service_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditauditlog',
            name='ref_type',
            field=models.CharField(blank=True, choices=[('payg', 'Pay-As-You-Go Purchase'), ('subscription', 'Subscription Purchase'), ('validation', 'Email Validation'), ('campaign', 'Campaign Send'), ('ip_check', 'IP/Domain/Header/Reputation Check'), ('admin', 'Admin Adjustment'), ('service_purchase', 'Service Credit Purchase'), ('so_account', 'Sales Outreach Account Added'), ('reputation', 'Reputation Analysis')], max_length=30),
        ),
    ]
