# Generated by Django 5.1.7 on 2026-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0133_creditauditlog_reputation_reftype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpackage',
            name='price_usd',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
