# Generated by Django 5.1.7 on 2026-09-02 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0135_fix_credit_package_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='trial_expiry_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('email_validation', 'Email Validation'), ('email_marketing', 'Email Marketing'), ('sales_outreach', 'Sales Outreach'), ('reputation', 'Reputation Analysis'), ('header_analysis', 'Email Header Analyzer'), ('ip_blocklist', 'IP Blocklist Monitor'), ('domain_blocklist', 'Domain Blocklist Monitor')], max_length=20)),
                ('limit', models.BigIntegerField(default=0)),
                ('used', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_trials',
                'indexes': [models.Index(fields=['user'], name='svc_trial_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'service'), name='uniq_service_trial_user_service'), models.CheckConstraint(condition=models.Q(('used__gte', 0)), name='service_trial_used_nonneg'), models.CheckConstraint(condition=models.Q(('used__lte', models.F('limit'))), name='service_trial_used_lte_limit')],
            },
        ),
        migrations.CreateModel(
            name='TrialUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('email_validation', 'Email Validation'), ('email_marketing', 'Email Marketing'), ('sales_outreach', 'Sales Outreach'), ('reputation', 'Reputation Analysis'), ('header_analysis', 'Email Header Analyzer'), ('ip_blocklist', 'IP Blocklist Monitor'), ('domain_blocklist', 'Domain Blocklist Monitor')], max_length=20)),
                ('entry_type', models.CharField(choices=[('granted', 'Trial Granted'), ('debit', 'Trial Credit Used'), ('expired', 'Trial Expired (unused allowance forfeited)')], max_length=10)),
                ('amount', models.IntegerField()),
                ('balance_before', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('ref_type', models.CharField(blank=True, max_length=30)),
                ('ref_id', models.CharField(blank=True, max_length=225)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trial_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'service', 'created_at'], name='trial_usage_user_id_55f8d3_idx'), models.Index(fields=['entry_type'], name='trial_usage_entry_t_338585_idx')],
            },
        ),
    ]
