# Generated by Django 5.1.7 on 2026-09-03 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0136_trial_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soemailaccountrotation',
            name='weight',
        ),
        migrations.AddField(
            model_name='socampaign',
            name='sender_send_count_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soemailaccountrotation',
            name='daily_send_count',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='soemailaccount',
            name='daily_limit',
            field=models.IntegerField(default=120),
        ),
        migrations.CreateModel(
            name='SOCampaignAccountDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_daily_usage', to='Email_validate_app.soemailaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_daily_usage', to='Email_validate_app.socampaign')),
            ],
            options={
                'db_table': 'so_campaign_account_daily_usage',
                'unique_together': {('campaign', 'account', 'date')},
            },
        ),
    ]
