# Generated by Django 5.1.7 on 2026-09-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0137_so_sender_send_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='daily_limit',
            field=models.IntegerField(default=120),
        ),
    ]
