# Generated by Django 6.0.3 on 2026-09-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0138_email_account_daily_limit_120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soconversation',
            name='thread_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
