# Generated by Django 5.1.7 on 2026-09-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0139_alter_soconversation_thread_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='soemailaccountwarmup',
            name='warmup_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='soemailaccountwarmup',
            name='warmup_subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
