# Generated by Django 5.1.7 on 2026-09-07 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0140_so_email_account_warmup_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
