# Generated by Django 5.1.7 on 2026-09-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0142_free_email_signup_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='soemailaccount',
            name='dkim_status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unchecked', 'Unchecked')], default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='soemailaccount',
            name='dmarc_status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unchecked', 'Unchecked')], default='unchecked', max_length=10),
        ),
        migrations.AddField(
            model_name='soemailaccount',
            name='spf_status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unchecked', 'Unchecked')], default='unchecked', max_length=10),
        ),
        migrations.AlterField(
            model_name='soevent',
            name='event_type',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('replied', 'Replied'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('soft_bounced', 'Soft Bounced'), ('complained', 'Complained')], max_length=20),
        ),
    ]
