# Generated by Django 5.1.7 on 2026-09-08 09:58

from django.db import migrations, models


def _enable_reply_to_where_already_set(apps, schema_editor):
    """New field, added on top of a Reply-To Address that has always been
    used unconditionally whenever set. Backfilling every existing non-blank
    reply_to to enabled=True (rather than leaving the new default of False
    for them too) is what actually satisfies "existing default behavior
    should work as it is" -- a campaign that already relies on its
    configured Reply-To must keep using it after this deploy, not silently
    stop until someone finds and flips the new toggle. A campaign with no
    reply_to is unaffected either way (enabled or not, nothing to use)."""
    SOCampaign = apps.get_model('Email_validate_app', 'SOCampaign')
    SOCampaign.objects.exclude(reply_to='').update(reply_to_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0143_soemailaccount_dkim_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socampaign',
            name='reply_to_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_enable_reply_to_where_already_set, migrations.RunPython.noop),
    ]
