# Generated by Django 5.1.7 on 2026-09-11 09:54

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0145_add_impersonation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistmonitor',
            name='entitlement_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='creditauditlog',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='Email_validate_app.creditauditlog'),
        ),
        migrations.AddField(
            model_name='creditauditlog',
            name='service',
            field=models.CharField(blank=True, choices=[('email_validation', 'Email Validation'), ('email_marketing', 'Email Marketing'), ('sales_outreach', 'Sales Outreach'), ('reputation', 'Reputation Analysis'), ('header_analysis', 'Email Header Analyzer'), ('ip_blocklist', 'IP Blocklist Monitor'), ('domain_blocklist', 'Domain Blocklist Monitor')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='creditauditlog',
            name='spend_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='domainblocklist',
            name='entitlement_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='reputation',
            name='entitlement_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='flow',
            field=models.CharField(choices=[('service_credits', 'Service Credits Checkout'), ('payg_ev', 'Email Validation Pay-As-You-Go')], default='service_credits', max_length=20),
        ),
        migrations.AddField(
            model_name='soemailaccount',
            name='entitlement_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='trialusagelog',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='Email_validate_app.trialusagelog'),
        ),
        migrations.AddField(
            model_name='trialusagelog',
            name='spend_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.CreateModel(
            name='ServiceCreditLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('email_validation', 'Email Validation'), ('email_marketing', 'Email Marketing'), ('sales_outreach', 'Sales Outreach'), ('reputation', 'Reputation Analysis'), ('header_analysis', 'Email Header Analyzer'), ('ip_blocklist', 'IP Blocklist Monitor'), ('domain_blocklist', 'Domain Blocklist Monitor')], max_length=20)),
                ('source', models.CharField(choices=[('service_checkout', 'Service Checkout'), ('payg_ev', 'Email Validation Pay-As-You-Go'), ('admin_adjustment', 'Admin Adjustment')], max_length=20)),
                ('quantity_purchased', models.BigIntegerField(default=0)),
                ('quantity_remaining', models.BigIntegerField(default=0)),
                ('quantity_used', models.BigIntegerField(default=0)),
                ('quantity_expired', models.BigIntegerField(default=0)),
                ('quantity_revoked', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('purchased_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='credit_lots', to='Email_validate_app.serviceorder')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='credit_lots', to='Email_validate_app.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_credit_lots',
            },
        ),
        migrations.AddField(
            model_name='creditauditlog',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='Email_validate_app.servicecreditlot'),
        ),
        migrations.CreateModel(
            name='ServiceEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('email_validation', 'Email Validation'), ('email_marketing', 'Email Marketing'), ('sales_outreach', 'Sales Outreach'), ('reputation', 'Reputation Analysis'), ('header_analysis', 'Email Header Analyzer'), ('ip_blocklist', 'IP Blocklist Monitor'), ('domain_blocklist', 'Domain Blocklist Monitor')], max_length=20)),
                ('funding_source', models.CharField(choices=[('lot', 'Credit Lot'), ('trial', 'Free Trial'), ('wallet', 'Grandfathered Wallet'), ('legacy_pool', 'Legacy Credit Pool'), ('grandfathered', 'Grandfathered (pre-rollout)')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('activated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('expired', 'Lot Expired'), ('trial_ended', 'Trial Ended'), ('removed', 'Removed by User'), ('revoked', 'Payment Revoked/Refunded'), ('admin', 'Admin Action')], max_length=15)),
                ('spend_id', models.CharField(blank=True, default='', max_length=36)),
                ('active_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='Email_validate_app.domainblocklist')),
                ('ip_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='Email_validate_app.blocklistmonitor')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entitlements', to='Email_validate_app.servicecreditlot')),
                ('reputation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='Email_validate_app.reputation')),
                ('so_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='Email_validate_app.soemailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_entitlements',
            },
        ),
        migrations.AddIndex(
            model_name='servicecreditlot',
            index=models.Index(fields=['user', 'service', 'status', 'expires_at'], name='cl_user_svc_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecreditlot',
            index=models.Index(fields=['status', 'expires_at'], name='credit_lot_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecreditlot',
            index=models.Index(fields=['payment'], name='credit_lot_payment_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicecreditlot',
            constraint=models.UniqueConstraint(fields=('payment', 'service'), name='uniq_credit_lot_payment_service'),
        ),
        migrations.AddConstraint(
            model_name='servicecreditlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_purchased__gte', 0)), name='credit_lot_purchased_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='servicecreditlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__gte', 0)), name='credit_lot_remaining_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='servicecreditlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_used__gte', 0)), name='credit_lot_used_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='servicecreditlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_expired__gte', 0)), name='credit_lot_expired_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='servicecreditlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_revoked__gte', 0)), name='credit_lot_revoked_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='servicecreditlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_purchased', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('quantity_remaining'), '+', models.F('quantity_used')), '+', models.F('quantity_expired')), '+', models.F('quantity_revoked')))), name='credit_lot_quantity_invariant'),
        ),
        migrations.AddIndex(
            model_name='serviceentitlement',
            index=models.Index(fields=['lot', 'status'], name='entitlement_lot_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceentitlement',
            index=models.Index(fields=['user', 'service', 'status'], name='ent_user_svc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceentitlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('domain_monitor__isnull', True), ('ip_monitor__isnull', False), ('reputation__isnull', True), ('so_account__isnull', True)), models.Q(('domain_monitor__isnull', False), ('ip_monitor__isnull', True), ('reputation__isnull', True), ('so_account__isnull', True)), models.Q(('domain_monitor__isnull', True), ('ip_monitor__isnull', True), ('reputation__isnull', False), ('so_account__isnull', True)), models.Q(('domain_monitor__isnull', True), ('ip_monitor__isnull', True), ('reputation__isnull', True), ('so_account__isnull', False)), _connector='OR'), name='entitlement_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='serviceentitlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('funding_source', 'lot'), ('lot__isnull', False)), models.Q(models.Q(('funding_source', 'lot'), _negated=True), ('lot__isnull', True)), _connector='OR'), name='entitlement_lot_required_iff_funding_lot'),
        ),
    ]
