# Generated by Django 5.1.7 on 2026-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0146_expiring_credit_lots_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='soemailaccountrotation',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
