# Generated by Django 5.1.7 on 2026-09-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_validate_app', '0147_soemailaccountrotation_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecreditlot',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
